var tags = [{"key": "#MeToo", "value": 71, "param": "coucou"}, 
{"key": "#YoTambién", "value": 39, "param": "hello"}, 
{"key": "#私も", "value": 37, "param": "coucou"},
{"key": "#balanceTonPorc", "value": 34, "param": "#BalanceTonPorc (#MoiAussi au Canada francophone) est un hashtag qui s'est largement diffusé sur les réseaux sociaux en octobre 2017 pour dénoncer l'agression sexuelle et le harcèlement, plus particulièrement dans le milieu professionnel, à la suite d'accusations de cette nature portées contre le producteur américain Harvey Weinstein. C'est la version francophone de la campagne MeToo, utilisée depuis 2007 en ce sens par l'activiste Tarana Burke et relancée en octobre 2017 sous forme du hashtag #MeToo (« moi aussi ») par l'actrice Alyssa Milano, qui a encouragé les femmes à partager sur Twitter leurs expériences."}, 
{"key": "#MoiAussi", "value": 32, "param": "coucou"},
{"key": "#我也是", "value": 24, "param": "coucou"}, 
{"key": "#QuellaVoltaChe", "value": 22, "param": "coucou"},
{"key": "#JoTambé", "value": 16, "param": "coucou"},
{"key": "#أنا_كمان", "value": 15, "param": "coucou"},
{"key": "#Ятоже", "value": 15, "param": "coucou"},  
{"key": "#NiEre", "value": 14, "param": "coucou"},
{"key": "#ماساكتاش", "value": 11, "param": "coucou"}, 
{"key": "#СегаКажувам", "value": 7, "param": "coucou"}, 
{"key": "#मैंभी", "value": 4, "param": "coucou"}, 
{"key": "#memyös", "value": 03, "param": "coucou"}, 
{"key": "#من_هم_همینطور", "value": 03, "param": "coucou"}, 
{"key": "#גםאנחנו", "value": 03, "param": "coucou"}, 
{"key": "#stilleføropptak", "value": 03, "param": "coucou"}, 
{"key": "#میں_بھی", "value": 03, "param": "coucou"}, 
{"key": "#나도당했다", "value": 03, "param": "coucou"}, 
{"key": "#TôiCũngVậy", "value": 03, "param": "coucou"}];